# This is the configuration file for litestream.
#
# For more details, see: https://litestream.io/reference/config/
#
dbs:
- path: $DATABASE_PATH
  replicas:
  - type: s3
    endpoint: $AWS_ENDPOINT_URL_S3
    bucket: $BUCKET_NAME
    path: litestream${DATABASE_PATH}
    access-key-id: $AWS_ACCESS_KEY_ID
    secret-access-key: $AWS_SECRET_ACCESS_KEY
    region: $AWS_REGION